setwd('E:/Projects/DQM/DQM Module/codes')
source('01_Data_import_Model_data_creation.R')
source('02_Dataset_summary_code.R')
source('03_Sampling_training_test.R')
source('04_Distribution_checks.R')
source('05_dv_univariate_check.R')
source('06_Missing_outlier_treatment.R')
source('07_Ranks_and_sums_data_creation.R')
source('08_Model_Validation_ Chart_data_creation.R')
source('09_variable_Transformation.R')
